/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'BT_2_stm32f205' 
 * Target:  'BT_2_stm32f205' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f2xx.h"



#endif /* RTE_COMPONENTS_H */
